### ISSUE TITLE
Schematron Issues

### ISSUE THREAD

**Issue by nlottig94** [nlottig94/Dickinson#2]
@RJP43 @brookestewart @ebeshero
Hi all! So, as you know, I am starting over on the encoding of Fascicle 16. I have noticed also that I never associated the Schematron to the old files...whoops :/. So I did for the new file and noticed that I'm getting errors because of the `var` xml:ids, which weren't xml:ids...soooo, I had to make a witness for each of the `vars` in the listWit and paste the relevant witnesses into each of the poems, where necessary, and now, the Schematron is valid!  If anybody has any issues, let me know!!  Also, I'm working from poem 1 onward so that I can have them encoded and ran through the XSLT before the conference.
This also sparks my curiosity...@ebeshero, will this affect the way the XSLT that we made works???  I'm going to have a look and let everyone know!

**Comment by ebeshero** [comment]
@nlottig94 Hi Nicole! Yes, I think we ought to expect some work yet to do with the XSLT, but maybe not very much! Keep us posted!

**Comment by nlottig94** [comment]
@ebeshero will do!!

**Comment by nlottig94** [comment]
@ebeshero @RJP43  @brookestewart 
Hello!!  I have just finished re-coding all of the Fascicle 16 poems!  I am taking a quick break, and then I am going to see what I can do with the XSLT!  Wish me luck!

**Comment by nlottig94** [comment]
@ebeshero @brookestewart @RJP43 
Hello all!!! The Fascicle 16 part of Dickinson is complete!!! The new HTMLs are up and running on the site!!  See you all in about a week!!!
