### ISSUE TITLE
Dickinson Updates

### ISSUE THREAD

**Issue by nlottig94** [nlottig94/Dickinson#6]
Hi all! (Well @RJP43 @brookestewart @ebeshero)

So throughout the past year-ish, I have compiled the manuscript images from the [Emily Dickinson Archive](http://www.edickinson.org/) for the first 19 Fascicles. This has taken a good deal of time, but we're about half way done with collecting the manuscript images!! Fascicle 20 is another story. I'm having difficulties viewing all the images so far, so I think I'm going to stop with the manuscript images for now and try to find the images from the other publications to add to our files. OR I may try to start transcribing and coding the poems starting from fascicle 1 (which is very exciting!)!

Okay, well I know it's been a while, so I thought I'd check in to let you know the minimal work I've been completing in my non-existent spare time!

**Comment by RJP43** [comment]
@nlottig94 Fantastic. I am so impressed that you have kept working on this knowing how busy you are. Thanks for keeping us updated. 👍

**Comment by ebeshero** [comment]
@nlottig94 Wow! You have been busy! It’s wonderful to see the Dickinson project continue on with new material. But what is the source of your images? When you say you are having trouble viewing the images,I am wondering what issues you are having—is it file size and format?

**Comment by nlottig94** [comment]
@ebeshero We have been getting the original manuscript images from the [Emily Dickinson Archive](http://www.edickinson.org/). The database recognizes the first lines of the poems that I am typing in and shows that there _should_ be images, but when I click on them, it says something along the lines of 'No image available.' This is something I can contact the database about, but I have many more poems than I can count with being able to find all the poems in the first nineteen fascicles, so I'm not too worried about that right this second. However, I am worried about finding the other publications that I have been using to compare variants because I don't have access to as many publications within public library systems as I had access to at Pitt.
